name: Daily updater

on: [push]
  #schedule:
    #- cron:  '20 01 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: What time is it ?
      run: |
        date -u
        TZ="Europe/Paris" date
    
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install prerequisites
      run: |
        cd /tmp/
        #sudo apt -qq update 
        #sudo apt -qq install -y python3 python3-pip python3-dev gcc libssl3 libssl-dev parallel ldnsutils
        
        python -m pip install -q --upgrade pip
        pip install -q n3map strip_markdown
        
        wget -nv "https://github.com/NLnetLabs/ldns/archive/refs/tags/1.8.3.zip"
        unzip -qq "./1.8.3.zip"
        cd "./ldns-1.8.3"
        libtoolize -ci
        autoreconf -fi
        ./configure --prefix=/tmp/ldns --with-examples --with-pyldns
        make && make install
        ls -alh /tmp/ldns/bin/ldns-walk

    - name: Prepare global variables
      run: | 
        echo "ZONES_DIR=$GITHUB_WORKSPACE/zones" >> $GITHUB_ENV
    
    - name: List and walk walkable zones
      run: |    
        cd /tmp
        wget -nv "https://github.com/monoidic/TLDR2/raw/master/walkable_zones.md"
        python -m strip_markdown "./walkable_zones.md"
        
        sed -i -e '/\.$/!d' -e '/^$/d' "./walkable_zones.txt"
        
        #cat walkable_zones.txt
        
        ldns-walk -version
        exit 1
        
        cd $GITHUB_WORKSPACE
        while IFS= read -r zone; do
          echo "$zone"
          [[ $zone == '.' ]] && zone='_rootzone'
          
          [[ -d "$ZONES_DIR/$zone" ]] || mkdir "$ZONES_DIR/$zone"
          CURRENT_ZONE_DIR="$ZONES_DIR/$zone"
                    
          [[ $zone == '_rootzone' ]] && zone='.'
          echo "CURRENT_ZONE_DIR: $CURRENT_ZONE_DIR | zone: $zone"
          
          cd "$CURRENT_ZONE_DIR"
          
          CURRENT_ZONE_ENUM="${CURRENT_ZONE_DIR}/${zone}zone"
          echo "CURRENT_ZONE_ENUM: $CURRENT_ZONE_ENUM"
          #n3map --help
          #time (timeout -s 9 5s n3map --quiet --no-prefix-labels --output "$CURRENT_ZONE_ENUM" "$zone")
          #n3map --quiet --no-prefix-labels --output "$zone"zone "$zone"
          #timeout -s 9 10s ldns-walk "$zone"
          ldns-walk "$zone" > CURRENT_ZONE_ENUM &
          echo
          #sed -e '/^[a-z]/!d' -e '/^$/d' "$CURRENT_ZONE_ENUM" | cut -f 1 | sed 's/\.$//' | sort -u
        
        done < "/tmp/walkable_zones.txt"
        
        #wait
        
        #git config user.name updating-bot
        #git config user.email github-actions@github.com
        #git commit -a -m "updating bot - $(date '+%Y/%m/%d')"
        #git pull
        #git push
        
        #cd $GITHUB_WORKSPACE
