name: Daily updater

on: [push]
  #schedule:
    #- cron:  '20 03 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: What time is it ?
      run: |
        date -u
        TZ="Europe/Paris" date
    
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install prerequisites
      run: |
        cd /tmp/

    - name: Prepare global variables
      run: | 
        echo "ZONES_DIR=$GITHUB_WORKSPACE/zones" >> $GITHUB_ENV
    
    - name: Rsync data
      env:
        SSH_REMOTE_SERVER_KEY: ${{ secrets.SSH_REMOTE_SERVER_KEY }}
      run: |    
        cd /tmp/
        echo "$SSH_REMOTE_SERVER_KEY" > /tmp/sshkey
        chmod 600 /tmp/sshkey
        
        # rsynced data is in /tmp/zones
        rsync -az -e "ssh -o LogLevel=quiet -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /tmp/sshkey" --progress dailynrdscan@ssh-dailynrdscan.alwaysdata.net:/home/dailynrdscan/www/zones .
        #ls -alhR ./zones
        
    - name: List and walk walkable zones
      run: | 
        
        cd /tmp/
        python -Wall "$GITHUB_WORKSPACE/_scripts/daily_merge.py" -f "/tmp/zones" -r "$ZONES_DIR" -d "/tmp/diff_results"
        ls -alh diff_results && wc diff_results 
        cat diff_results
      
        exit 1
      
        #git config user.name updating-bot
        #git config user.email github-actions@github.com
        #git commit -a -m "updating bot - $(date '+%Y/%m/%d')"
        #git pull
        #git push
        
        #cd $GITHUB_WORKSPACE
