name: Daily updater

on: [push]
  #schedule:
    #- cron:  '20 03 * * *'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: What time is it ?
      run: |
        date -u
        TZ="Europe/Paris" date
    
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install prerequisites
      run: |
        sudo apt -qq install fd-find

    - name: Prepare global variables
      run: | 
        echo "ZONES_DIR=$GITHUB_WORKSPACE/zones" >> $GITHUB_ENV
        echo "DAILY_DIR=$GITHUB_WORKSPACE/daily" >> $GITHUB_ENV
    
    - name: Rsync data
      env:
        SSH_REMOTE_SERVER_KEY: ${{ secrets.SSH_REMOTE_SERVER_KEY }}
      run: |    
        cd /tmp/
        echo "$SSH_REMOTE_SERVER_KEY" > /tmp/sshkey
        chmod 600 /tmp/sshkey
        
        # rsynced data is in /tmp/zones
        rsync -az -e "ssh -o LogLevel=quiet -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /tmp/sshkey" --progress dailynrdscan@ssh-dailynrdscan.alwaysdata.net:/home/dailynrdscan/www/zones .
        #ls -alhR ./zones
        
    - name: List and walk walkable zones
      run: | 
        
        cd /tmp/
        python -Wall "$GITHUB_WORKSPACE/_scripts/daily_merge.py" -f "/tmp/zones" -r "$ZONES_DIR"
        
        cd "$ZONES_DIR"
        ls -alR
        zcat ./audio/today_new.gz
      
    - name: Generate today_new and yesterday_new files 
      run: |
        #cd "$DAILY_DIR"
        cd /tmp/
        which fdfind
        which zcat
        fdfind $TMP
        fdfind "$TMP"
        #fdfind --help
        #fdfind -a -g 'today_new.gz' "$ZONES_DIR"
        #fdfind -a -g 'today_new.gz' "$ZONES_DIR" -x ls -alh
        fdfind -a -g 'today_new.gz' "$ZONES_DIR" -x /usr/bin/zcat
        (fdfind -a -g 'today_new.gz' "$ZONES_DIR" -x zcat {}) | tee | gzip > "./today_new.gz"
        
        #fdfind -a -g 'yesterday_new.gz' "$ZONES_DIR"
        (fdfind -a -g 'yesterday_new.gz' "$ZONES_DIR" -x zcat {}) | tee
        (fdfind -a -g 'yesterday_new.gz' "$ZONES_DIR" -x zcat {}) | tee | gzip > "./yesterday_new.gz"
        
        ls -alh "./today_new.gz"
        ls -alh "./yesterday_new.gz"
        
        readlink -f "./today_new.gz"
        readlink -f "./yesterday_new.gz"
          
    - name: Git commit 
      run: |
        git config user.name updating-bot
        git config user.email github-actions@github.com
        
        cd "$ZONES_DIR"
        git add ./*
        
        cd "$DAILY_DIR"
        git add "./today_new.gz" "./yesterday_new.gz" 
        
        git commit -a -m "updating bot - $(date '+%Y/%m/%d')"
        git pull
        git push
